"""Portal-facing supervisor contract deliberately excludes command execution."""

from __future__ import annotations
from typing import Protocol
from .models import LifecycleResult, ProcessState, RegisteredBot


class Supervisor(Protocol):
    def list_bots(self) -> tuple[RegisteredBot, ...]: ...
    def get_bot(self, bot_id: str) -> RegisteredBot: ...
    def get_process_state(self, bot_id: str) -> ProcessState: ...
    async def start(self, bot_id: str, *, actor: str | None = None) -> LifecycleResult: ...
    async def stop(self, bot_id: str, *, actor: str | None = None) -> LifecycleResult: ...
    async def restart(self, bot_id: str, *, actor: str | None = None) -> LifecycleResult: ...
