"""Portal-facing supervisor contract deliberately excludes command execution."""

from __future__ import annotations
from typing import Protocol
from shared.bot_core import BotStatus


class Supervisor(Protocol):
    async def status(self, bot_id: str) -> BotStatus: ...
    async def start(self, bot_id: str) -> BotStatus: ...
    async def stop(self, bot_id: str) -> BotStatus: ...
    async def restart(self, bot_id: str) -> BotStatus: ...
